server {
    listen 8080;
    server_name localhost;

    #the internal DNS resolver for docker/railway
    resolver 127.0.0.11 valid=30s;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /predict {
        #This prevents nginx from crashing if backend is slow to start (cold-starting)
        set $backend_link http://anchor.railway.internal:8000/predict;
        proxy_pass $backend_link;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
